-- languages
DROP TABLE IF EXISTS `languages`;
CREATE TABLE `languages` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`code`)
) ENGINE = InnoDB;

-- users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `language` VARCHAR(2) NOT NULL DEFAULT 'en',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (language) REFERENCES languages(code)
) ENGINE = InnoDB;

-- emojis
DROP TABLE IF EXISTS `emojis`;
CREATE TABLE `emojis` (
  `code` VARCHAR(64) NOT NULL,
  `character` VARCHAR(1) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`code`)
) ENGINE = InnoDB;
